[package]
name = "pybites-rust-download"
version = "0.1.3"
edition = "2024"

[dependencies]
reqwest = { version="0.12.23" , features = ["blocking", "json"]}
serde = { version = "1.0.227", features = ["derive"] }

[[bin]]
name = "pybites-rust-download"
path = "src/main.rs"
